// <auto-generated />
using System;
using DataEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntity.Migrations
{
    [DbContext(typeof(PujcovnaContext))]
    [Migration("20251210104613_PridaniCeny")]
    partial class PridaniCeny
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataEntity.Naradi", b =>
                {
                    b.Property<int>("NaradiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NaradiId"));

                    b.Property<int>("CenaZaDen")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hmotnost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeDostupne")
                        .HasColumnType("bit");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Popis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Umisteni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vykon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NaradiId");

                    b.ToTable("Naradi");
                });

            modelBuilder.Entity("DataEntity.Vypujcka", b =>
                {
                    b.Property<int>("VypujckaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VypujckaId"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumVraceniPlan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumVraceniSkutecne")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVypujcky")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<int>("NaradiId")
                        .HasColumnType("int");

                    b.Property<decimal>("Penale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ZakaznikId")
                        .HasColumnType("int");

                    b.HasKey("VypujckaId");

                    b.HasIndex("NaradiId");

                    b.HasIndex("ZakaznikId");

                    b.ToTable("Vypujcky");
                });

            modelBuilder.Entity("DataEntity.Zakaznik", b =>
                {
                    b.Property<int>("ZakaznikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZakaznikId"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ban")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Organizace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poznamka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TelefonniCislo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ZakaznikId");

                    b.ToTable("Zakaznici");
                });

            modelBuilder.Entity("DataEntity.Vypujcka", b =>
                {
                    b.HasOne("DataEntity.Naradi", "Naradi")
                        .WithMany("Vypujcky")
                        .HasForeignKey("NaradiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataEntity.Zakaznik", "Zakaznik")
                        .WithMany("Vypujcky")
                        .HasForeignKey("ZakaznikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naradi");

                    b.Navigation("Zakaznik");
                });

            modelBuilder.Entity("DataEntity.Naradi", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("DataEntity.Zakaznik", b =>
                {
                    b.Navigation("Vypujcky");
                });
#pragma warning restore 612, 618
        }
    }
}
