// <auto-generated />
using System;
using DataEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntity.Migrations
{
    [DbContext(typeof(PujcovnaContext))]
    [Migration("20251229214505_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataEntity.Data.Naradi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaZaDen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Dostupnost")
                        .HasColumnType("bit");

                    b.Property<string>("Hmotnost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poznamka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Umisteni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vykon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Naradi");
                });

            modelBuilder.Entity("DataEntity.Data.Vypujcka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumVraceniPlan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumVraceniSkutecne")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumVypujcky")
                        .HasColumnType("datetime2");

                    b.Property<int>("NaradiId")
                        .HasColumnType("int");

                    b.Property<decimal>("Penale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ZakaznikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NaradiId");

                    b.HasIndex("ZakaznikId");

                    b.ToTable("Vypujcky");
                });

            modelBuilder.Entity("DataEntity.Data.Zakaznik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ban")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organizace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poznamka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zakaznici");
                });

            modelBuilder.Entity("DataEntity.Data.Vypujcka", b =>
                {
                    b.HasOne("DataEntity.Data.Naradi", "Naradi")
                        .WithMany("Vypujcky")
                        .HasForeignKey("NaradiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataEntity.Data.Zakaznik", "Zakaznik")
                        .WithMany("Vypujcky")
                        .HasForeignKey("ZakaznikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naradi");

                    b.Navigation("Zakaznik");
                });

            modelBuilder.Entity("DataEntity.Data.Naradi", b =>
                {
                    b.Navigation("Vypujcky");
                });

            modelBuilder.Entity("DataEntity.Data.Zakaznik", b =>
                {
                    b.Navigation("Vypujcky");
                });
#pragma warning restore 612, 618
        }
    }
}
